export const BACK = 'Back'
export const NEXT = 'Next'
export const GENERATE_WORKOUT = 'Generate Workout'
export const REFRESH = 'Refresh'
export const COMPLETE_SET = 'Complete Set '
export const COMPLETE_WORKOUT = 'Complete Workout'
export const BEGIN_WORKOUT = 'Begin Workout'