export const HOME = 'Home'
export const TRAINING_GOALS = 'TrainingGoals'
export const EQUIPMENT_LIST = 'EquipmentList'
export const MUSCLE_GROUP = 'MuscleGroup'
export const LEVELS = 'Levels'
export const GENERATED_WORKOUT = 'GeneratedWorkout'
export const BEGIN_WORKOUT = 'BeginWorkoutScreen'