export const UPDATE_TRAINING_GOAL = 'UPDATE_TRAINING_GOAL'
export const UPDATE_GOALS = 'UPDATE_GOALS'
export const SET_EQUIPMENT_LIST = 'SET_EQUIPMENT_LIST'
export const SELECTED_EQUIPMENT_LIST = 'SELECTED_EQUIPMENT_LIST'